routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
Route::get('/', function () {
    return view('welcome');
});

*/

Auth::routes(['verify' => true]);

Route::get('/', 'HomeController@index')->name('home');

//Route::get('/', 'HomeController@index')->name('home')->middleware('verified');



Route::middleware('admin')->group(function () {
    Route::resource ('category', 'CategoryController', [
        'except' => 'show'
    ]);
});


Route::middleware ('auth', 'verified')->group (function () {
    Route::resource ('image', 'ImageController', [
        'only' => ['create', 'store', 'destroy', 'update']
    ]);
});

Route::name('category')->get('category/{slug}', 'ImageController@category');

Route::name ('user')->get ('user/{user}', 'ImageController@user');

Route::name ('image.')->middleware ('ajax')->group (function () {
    Route::prefix('image')->group(function () {
        Route::name ('description')->put ('{image}/description', 'ImageController@descriptionUpdate');
        Route::name ('adult')->put ('{image}/adult', 'ImageController@adultUpdate');

    });
});


Route::middleware ('auth', 'verified')->group (function () {
    Route::resource('profile', 'ProfileController', [
        'only' => ['edit', 'update', 'destroy', 'show'],
        'parameters' => ['profile' => 'user']
    ]);
});

Route::middleware ('auth', 'verified')->group (function () {
    Route::resource('album', 'AlbumController', [
        'except' => 'show'
    ]);
}) ;

Route::name ('album')->get ('album/{slug}', 'ImageController@album');

app/models/Album.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Events\NameSaving;


class Album extends Model
{
    protected $fillable = [
        'name', 'slug',
    ];
    protected $dispatchesEvents = [
        'saving' => NameSaving::class,
    ];
    public function images()
    {
        return $this->belongsToMany (Image::class);
    }
    public function user()
    {
        return $this->belongsTo (User::class);
    }


}

app/Http/Controllers/AlbumController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Album;
use App\Http\Requests\AlbumRequest;
use App\Repositories\AlbumRepository;

class AlbumController extends Controller
{

    protected $repositoryAlbum;

    public function __construct(AlbumRepository $repository)
    {
        $this->repositoryAlbum = $repository;
        $this->middleware('ajax')->only('destroy');

    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $userAlbums = $this->repositoryAlbum->getAlbums($request->user());
        return view('albums.index', compact('userAlbums'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('albums.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */

    public function store(AlbumRequest $request)
    {
        $this->repositoryAlbum->create($request->user(), $request->all());
        return back()->with('ok', __("L'album a bien été enregistré"));
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Album $album)
    {
        return view ('albums.edit', compact ('album'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(AlbumRequest $request, Album $album)
    {
        $this->authorize('manage', $album);
        $album->update($request->all());
        return redirect()->route('album.index')->with('ok', __("L'album a bien été modifié"));
    }
        /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Album $album)
    {
        $this->authorize('manage', $album);
        $album->delete();
        return response()->json();

    }
}

resources/views/albums/create.blade.php
@extends('layouts.form')
@section('card')
    @component('components.card')
        @slot('title')
            @lang('Ajouter un album')
        @endslot
        <form method="POST" action="{{ route('album.store') }}">
            @csrf
            @include('partials.form-group', [
                'title' => __('Nom'),
                'type' => 'text',
                'name' => 'name',
                'required' => true,
                ])
            @component('components.button')
                @lang('Envoyer')
            @endcomponent
        </form>
    @endcomponent
@endsection

resources/views/albums/edit.blade.php
@extends('layouts.form')
@section('card')
    @component('components.card')
        @slot('title')
            @lang('Modifier un album')
        @endslot
        <form method="POST" action="{{ route('album.update', $album->id) }}">
            @csrf
            @method('PUT')
            @include('partials.form-group', [
                'title' => __('Nom'),
                'type' => 'text',
                'name' => 'name',
                'value' => $album->name,
                'required' => true,
                ])
            @component('components.button')
                @lang('Envoyer')
            @endcomponent
        </form>
    @endcomponent
@endsection

resources/views/albums/index.blade.php
@extends('layouts.form')
@section('card')
    @component('components.card')
        @slot('title')
            @lang('Gestion des albums')
        @endslot
        <table class="table table-dark text-white">
            <tbody>
            @if($userAlbums->isEmpty())
                <p class="text-center">@lang("Vous n'avez aucun album pour le moment")</p>
            @else
                @foreach($userAlbums as $album)
                    <tr>
                        <td>{{ $album->name }}</td>
                        <td>
                            <a type="button" href="{{ route('album.destroy', $album->id) }}"
                               class="btn btn-danger btn-sm pull-right invisible" data-toggle="tooltip"
                               title="@lang("Supprimer l'album") {{ $album->name }}"><i
                                    class="fas fa-trash fa-lg"></i></a>
                            <a type="button" href="{{ route('album.edit', $album->id) }}"
                               class="btn btn-warning btn-sm pull-right mr-2 invisible" data-toggle="tooltip"
                               title="@lang("Modifier l'album") {{ $album->name }}"><i
                                    class="fas fa-edit fa-lg"></i></a>
                        </td>
                    </tr>
                @endforeach
            @endif
            </tbody>
        </table>
    @endcomponent
@endsection
@section('script')
    <script>
        $(() => {
            $('a').removeClass('invisible')
        })
    </script>
    @include('partials.script-delete', ['text' => __('Vraiment supprimer cet album ?'), 'return' => 'removeTr'])
@endsection